export const REQUEST_LIST_USER = 'REQUEST_LIST_USER';
export const RECIVE_LIST_USER = 'RECEVE_LIST_USER';
export const REQUEST_ADD_USER = 'REQUEST_ADD_USER';
export const REQUEST_DETELE_POST = 'REQUEST_DETELE_POST';